#!/bin/bash

# Check if both RESOURCE_TYPE and NAMESPACE are provided as arguments
if [ $# -ne 2 ]; then
  echo "Usage: $0 <RESOURCE_TYPE> <NAMESPACE>"
  exit 1
fi

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
OUTPUT=$(kubectl top $RESOURCE_TYPE -n $NAMESPACE)
if [ $? -eq 0 ]; then
  echo "$OUTPUT" | tail -n+2 | while read line
  do
    # Extract CPU and memory usage from the output
    NAME=$(echo $line | awk '{print $1}')
    CPU=$(echo $line | awk '{print $3}')
    MEMORY=$(echo $line | awk '{print $5}')

    # Output the statistics to the console
    echo $RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY
  done
else
  echo -n "$OUTPUT"
fi
